// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
	require('../src/components/AddressItem/__stories__/AddressItem.stories');
	require('../src/components/AddressRadioGroup/__stories__/AddressRadioGroup.stories');
	require('../src/components/AvatarVariantSelectorItem/__stories__/AvatarVariantSelectorItem.stories');
	require('../src/components/CityPicker/__stories__/CityPicker.stories');
	require('../src/components/ColorVariantSelectorItem/__stories__/ColorVariantSelectorItem.stories');
	require('../src/components/CommiFooter/__stories__/CommiFooter.stories');
	require('../src/components/CommiFooter/__stories__/FooterAppDownloadLinks.stories');
	require('../src/components/CommiFooter/__stories__/FooterCopyright.stories');
	require('../src/components/CommiFooter/__stories__/FooterLinkList.stories');
	require('../src/components/CommiFooter/__stories__/FooterOverviewSection.stories');
	require('../src/components/CommiFooter/__stories__/FooterPartnerBrands.stories');
	require('../src/components/CommiFooter/__stories__/FooterSocialLinks.stories');
	require('../src/components/CommiHeader/__stories__/CartButton.stories');
	require('../src/components/CommiHeader/__stories__/CommiHeader.stories');
	require('../src/components/CommiHeader/__stories__/HeaderLogo.stories');
	require('../src/components/CommiHeader/__stories__/HeaderMenuItem.stories');
	require('../src/components/CommiHeader/__stories__/HeaderMenuSubList.stories');
	require('../src/components/CommiHeader/__stories__/MegaMenu.stories');
	require('../src/components/CommiHeader/__stories__/UserMenu.stories');
	require('../src/components/Features/__stories__/FeatureItem.stories');
	require('../src/components/Features/__stories__/FeatureItemCollapsible.stories');
	require('../src/components/Features/__stories__/FeatureList.stories');
	require('../src/components/Features/__stories__/FeatureListCollapsible.stories');
	require('../src/components/Features/__stories__/Features.stories');
	require('../src/components/ImageVariantSelectorItem/__stories__/ImageVariantSelectorItem.stories');
	require('../src/components/MediaSlider/__stories__/MediaSlider.stories');
	require('../src/components/MediaSlider/__stories__/Pagination.stories');
	require('../src/components/MediaSlider/__stories__/PaginationDot.stories');
	require('../src/components/MiniList/__stories__/MiniList.stories');
	require('../src/components/MiniListItem/__stories__/MiniListItem.stories');
	require('../src/components/MultiLevelSelector/__stories__/List.stories');
	require('../src/components/MultiLevelSelector/__stories__/ListItem.stories');
	require('../src/components/MultiLevelSelector/__stories__/MultiLevelSelector.stories');
	require('../src/components/MultiLevelSelector/__stories__/SlidingPane.stories');
	require('../src/components/OrderList/__stories__/OrderList.stories');
	require('../src/components/OrderListEmptyState/__stories__/OrderListEmptyState.stories');
	require('../src/components/OrderListItem/__stories__/OrderListItem.stories');
	require('../src/components/PaymentMethodList/__stories__/PaymentMethodList.stories');
	require('../src/components/PaymentMethodListEmptyState/__stories__/PaymentMethodListEmptyState.stories');
	require('../src/components/PaymentMethodListItem/__stories__/PaymentMethodListItem.stories');
	require('../src/components/PaymentMethodPicker/__stories__/PaymentMethodPicker.stories');
	require('../src/components/Price/__stories__/Price.stories');
	require('../src/components/PricingTable/__stories__/PricingTable.stories');
	require('../src/components/ProductVariantInfo/__stories__/ProductVariantInfo.stories');
	require('../src/components/ShippingMethodList/__stories__/ShippingMethodList.stories');
	require('../src/components/ShippingMethodListEmptyState/__stories__/ShippingMethodListEmptyState.stories');
	require('../src/components/ShippingMethodListItem/__stories__/ShippingMethodListItem.stories');
	require('../src/components/ShippingMethodPicker/__stories__/ShippingMethodPicker.stories');
	require('../src/components/Specifications/__stories__/SpecificationGroup.stories');
	require('../src/components/Specifications/__stories__/SpecificationItem.stories');
	require('../src/components/Specifications/__stories__/Specifications.stories');
	require('../src/components/StatusBadge/__stories__/StatusBadge.stories');
	require('../src/components/StoreInfo/__stories__/StoreInfo.stories');
	require('../src/components/TextVariantSelectorItem/__stories__/TextVariantSelectorItem.stories');
	require('../src/components/VariantSelector/__stories__/VariantSelector.stories');
}

const stories = [
	'../src/components/AddressItem/__stories__/AddressItem.stories',
	'../src/components/AddressRadioGroup/__stories__/AddressRadioGroup.stories',
	'../src/components/AvatarVariantSelectorItem/__stories__/AvatarVariantSelectorItem.stories',
	'../src/components/CityPicker/__stories__/CityPicker.stories',
	'../src/components/ColorVariantSelectorItem/__stories__/ColorVariantSelectorItem.stories',
	'../src/components/CommiFooter/__stories__/CommiFooter.stories',
	'../src/components/CommiFooter/__stories__/FooterAppDownloadLinks.stories',
	'../src/components/CommiFooter/__stories__/FooterCopyright.stories',
	'../src/components/CommiFooter/__stories__/FooterLinkList.stories',
	'../src/components/CommiFooter/__stories__/FooterOverviewSection.stories',
	'../src/components/CommiFooter/__stories__/FooterPartnerBrands.stories',
	'../src/components/CommiFooter/__stories__/FooterSocialLinks.stories',
	'../src/components/CommiHeader/__stories__/CartButton.stories',
	'../src/components/CommiHeader/__stories__/CommiHeader.stories',
	'../src/components/CommiHeader/__stories__/HeaderLogo.stories',
	'../src/components/CommiHeader/__stories__/HeaderMenuItem.stories',
	'../src/components/CommiHeader/__stories__/HeaderMenuSubList.stories',
	'../src/components/CommiHeader/__stories__/MegaMenu.stories',
	'../src/components/CommiHeader/__stories__/UserMenu.stories',
	'../src/components/Features/__stories__/FeatureItem.stories',
	'../src/components/Features/__stories__/FeatureItemCollapsible.stories',
	'../src/components/Features/__stories__/FeatureList.stories',
	'../src/components/Features/__stories__/FeatureListCollapsible.stories',
	'../src/components/Features/__stories__/Features.stories',
	'../src/components/ImageVariantSelectorItem/__stories__/ImageVariantSelectorItem.stories',
	'../src/components/MediaSlider/__stories__/MediaSlider.stories',
	'../src/components/MediaSlider/__stories__/Pagination.stories',
	'../src/components/MediaSlider/__stories__/PaginationDot.stories',
	'../src/components/MiniList/__stories__/MiniList.stories',
	'../src/components/MiniListItem/__stories__/MiniListItem.stories',
	'../src/components/MultiLevelSelector/__stories__/List.stories',
	'../src/components/MultiLevelSelector/__stories__/ListItem.stories',
	'../src/components/MultiLevelSelector/__stories__/MultiLevelSelector.stories',
	'../src/components/MultiLevelSelector/__stories__/SlidingPane.stories',
	'../src/components/OrderList/__stories__/OrderList.stories',
	'../src/components/OrderListEmptyState/__stories__/OrderListEmptyState.stories',
	'../src/components/OrderListItem/__stories__/OrderListItem.stories',
	'../src/components/PaymentMethodList/__stories__/PaymentMethodList.stories',
	'../src/components/PaymentMethodListEmptyState/__stories__/PaymentMethodListEmptyState.stories',
	'../src/components/PaymentMethodListItem/__stories__/PaymentMethodListItem.stories',
	'../src/components/PaymentMethodPicker/__stories__/PaymentMethodPicker.stories',
	'../src/components/Price/__stories__/Price.stories',
	'../src/components/PricingTable/__stories__/PricingTable.stories',
	'../src/components/ProductVariantInfo/__stories__/ProductVariantInfo.stories',
	'../src/components/ShippingMethodList/__stories__/ShippingMethodList.stories',
	'../src/components/ShippingMethodListEmptyState/__stories__/ShippingMethodListEmptyState.stories',
	'../src/components/ShippingMethodListItem/__stories__/ShippingMethodListItem.stories',
	'../src/components/ShippingMethodPicker/__stories__/ShippingMethodPicker.stories',
	'../src/components/Specifications/__stories__/SpecificationGroup.stories',
	'../src/components/Specifications/__stories__/SpecificationItem.stories',
	'../src/components/Specifications/__stories__/Specifications.stories',
	'../src/components/StatusBadge/__stories__/StatusBadge.stories',
	'../src/components/StoreInfo/__stories__/StoreInfo.stories',
	'../src/components/TextVariantSelectorItem/__stories__/TextVariantSelectorItem.stories',
	'../src/components/VariantSelector/__stories__/VariantSelector.stories',
];

module.exports = {
	loadStories,
	stories,
};
